//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("creo_dataModel", "FK_MACHINED_REFERENCE_MACHINES", "machines", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.machines), "machineDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.machineDetail), true)]
[assembly: EdmRelationshipAttribute("creo_dataModel", "FK_TOOLDETA_REFERENCE_TOOLS", "tools", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.tools), "toolDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.toolDetail), true)]
[assembly: EdmRelationshipAttribute("creo_dataModel", "FK_PARAMETE_REFERENCE_MEMBER", "member", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.member), "parameters", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.parameters), true)]

#endregion

namespace Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class creo_dataEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“creo_dataEntities”部分中的连接字符串初始化新 creo_dataEntities 对象。
        /// </summary>
        public creo_dataEntities() : base("name=creo_dataEntities", "creo_dataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 creo_dataEntities 对象。
        /// </summary>
        public creo_dataEntities(string connectionString) : base(connectionString, "creo_dataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 creo_dataEntities 对象。
        /// </summary>
        public creo_dataEntities(EntityConnection connection) : base(connection, "creo_dataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<machineDetail> machineDetail
        {
            get
            {
                if ((_machineDetail == null))
                {
                    _machineDetail = base.CreateObjectSet<machineDetail>("machineDetail");
                }
                return _machineDetail;
            }
        }
        private ObjectSet<machineDetail> _machineDetail;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<machines> machines
        {
            get
            {
                if ((_machines == null))
                {
                    _machines = base.CreateObjectSet<machines>("machines");
                }
                return _machines;
            }
        }
        private ObjectSet<machines> _machines;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<process> process
        {
            get
            {
                if ((_process == null))
                {
                    _process = base.CreateObjectSet<process>("process");
                }
                return _process;
            }
        }
        private ObjectSet<process> _process;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<toolDetail> toolDetail
        {
            get
            {
                if ((_toolDetail == null))
                {
                    _toolDetail = base.CreateObjectSet<toolDetail>("toolDetail");
                }
                return _toolDetail;
            }
        }
        private ObjectSet<toolDetail> _toolDetail;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tools> tools
        {
            get
            {
                if ((_tools == null))
                {
                    _tools = base.CreateObjectSet<tools>("tools");
                }
                return _tools;
            }
        }
        private ObjectSet<tools> _tools;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<member> member
        {
            get
            {
                if ((_member == null))
                {
                    _member = base.CreateObjectSet<member>("member");
                }
                return _member;
            }
        }
        private ObjectSet<member> _member;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<parameters> parameters
        {
            get
            {
                if ((_parameters == null))
                {
                    _parameters = base.CreateObjectSet<parameters>("parameters");
                }
                return _parameters;
            }
        }
        private ObjectSet<parameters> _parameters;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 machineDetail EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomachineDetail(machineDetail machineDetail)
        {
            base.AddObject("machineDetail", machineDetail);
        }
    
        /// <summary>
        /// 用于向 machines EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomachines(machines machines)
        {
            base.AddObject("machines", machines);
        }
    
        /// <summary>
        /// 用于向 process EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToprocess(process process)
        {
            base.AddObject("process", process);
        }
    
        /// <summary>
        /// 用于向 toolDetail EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotoolDetail(toolDetail toolDetail)
        {
            base.AddObject("toolDetail", toolDetail);
        }
    
        /// <summary>
        /// 用于向 tools EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotools(tools tools)
        {
            base.AddObject("tools", tools);
        }
    
        /// <summary>
        /// 用于向 member EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomember(member member)
        {
            base.AddObject("member", member);
        }
    
        /// <summary>
        /// 用于向 parameters EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToparameters(parameters parameters)
        {
            base.AddObject("parameters", parameters);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="creo_dataModel", Name="machineDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class machineDetail : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 machineDetail 对象。
        /// </summary>
        /// <param name="madeId">madeId 属性的初始值。</param>
        /// <param name="isDelete">isDelete 属性的初始值。</param>
        public static machineDetail CreatemachineDetail(global::System.Int32 madeId, global::System.Int32 isDelete)
        {
            machineDetail machineDetail = new machineDetail();
            machineDetail.madeId = madeId;
            machineDetail.isDelete = isDelete;
            return machineDetail;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 madeId
        {
            get
            {
                return _madeId;
            }
            set
            {
                if (_madeId != value)
                {
                    OnmadeIdChanging(value);
                    ReportPropertyChanging("madeId");
                    _madeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("madeId");
                    OnmadeIdChanged();
                }
            }
        }
        private global::System.Int32 _madeId;
        partial void OnmadeIdChanging(global::System.Int32 value);
        partial void OnmadeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> machId
        {
            get
            {
                return _machId;
            }
            set
            {
                OnmachIdChanging(value);
                ReportPropertyChanging("machId");
                _machId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("machId");
                OnmachIdChanged();
            }
        }
        private Nullable<global::System.Int32> _machId;
        partial void OnmachIdChanging(Nullable<global::System.Int32> value);
        partial void OnmachIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String machPara
        {
            get
            {
                return _machPara;
            }
            set
            {
                OnmachParaChanging(value);
                ReportPropertyChanging("machPara");
                _machPara = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("machPara");
                OnmachParaChanged();
            }
        }
        private global::System.String _machPara;
        partial void OnmachParaChanging(global::System.String value);
        partial void OnmachParaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String machParaValue
        {
            get
            {
                return _machParaValue;
            }
            set
            {
                OnmachParaValueChanging(value);
                ReportPropertyChanging("machParaValue");
                _machParaValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("machParaValue");
                OnmachParaValueChanged();
            }
        }
        private global::System.String _machParaValue;
        partial void OnmachParaValueChanging(global::System.String value);
        partial void OnmachParaValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 isDelete
        {
            get
            {
                return _isDelete;
            }
            set
            {
                OnisDeleteChanging(value);
                ReportPropertyChanging("isDelete");
                _isDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isDelete");
                OnisDeleteChanged();
            }
        }
        private global::System.Int32 _isDelete;
        partial void OnisDeleteChanging(global::System.Int32 value);
        partial void OnisDeleteChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("creo_dataModel", "FK_MACHINED_REFERENCE_MACHINES", "machines")]
        public machines machines
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<machines>("creo_dataModel.FK_MACHINED_REFERENCE_MACHINES", "machines").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<machines>("creo_dataModel.FK_MACHINED_REFERENCE_MACHINES", "machines").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<machines> machinesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<machines>("creo_dataModel.FK_MACHINED_REFERENCE_MACHINES", "machines");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<machines>("creo_dataModel.FK_MACHINED_REFERENCE_MACHINES", "machines", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="creo_dataModel", Name="machines")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class machines : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 machines 对象。
        /// </summary>
        /// <param name="machId">machId 属性的初始值。</param>
        /// <param name="isDelete">isDelete 属性的初始值。</param>
        public static machines Createmachines(global::System.Int32 machId, global::System.Int32 isDelete)
        {
            machines machines = new machines();
            machines.machId = machId;
            machines.isDelete = isDelete;
            return machines;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 machId
        {
            get
            {
                return _machId;
            }
            set
            {
                if (_machId != value)
                {
                    OnmachIdChanging(value);
                    ReportPropertyChanging("machId");
                    _machId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("machId");
                    OnmachIdChanged();
                }
            }
        }
        private global::System.Int32 _machId;
        partial void OnmachIdChanging(global::System.Int32 value);
        partial void OnmachIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String machName
        {
            get
            {
                return _machName;
            }
            set
            {
                OnmachNameChanging(value);
                ReportPropertyChanging("machName");
                _machName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("machName");
                OnmachNameChanged();
            }
        }
        private global::System.String _machName;
        partial void OnmachNameChanging(global::System.String value);
        partial void OnmachNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 isDelete
        {
            get
            {
                return _isDelete;
            }
            set
            {
                OnisDeleteChanging(value);
                ReportPropertyChanging("isDelete");
                _isDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isDelete");
                OnisDeleteChanged();
            }
        }
        private global::System.Int32 _isDelete;
        partial void OnisDeleteChanging(global::System.Int32 value);
        partial void OnisDeleteChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String picName
        {
            get
            {
                return _picName;
            }
            set
            {
                OnpicNameChanging(value);
                ReportPropertyChanging("picName");
                _picName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("picName");
                OnpicNameChanged();
            }
        }
        private global::System.String _picName;
        partial void OnpicNameChanging(global::System.String value);
        partial void OnpicNameChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("creo_dataModel", "FK_MACHINED_REFERENCE_MACHINES", "machineDetail")]
        public EntityCollection<machineDetail> machineDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<machineDetail>("creo_dataModel.FK_MACHINED_REFERENCE_MACHINES", "machineDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<machineDetail>("creo_dataModel.FK_MACHINED_REFERENCE_MACHINES", "machineDetail", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="creo_dataModel", Name="member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class member : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 member 对象。
        /// </summary>
        /// <param name="mem_id">mem_id 属性的初始值。</param>
        /// <param name="isWork">isWork 属性的初始值。</param>
        public static member Createmember(global::System.Int32 mem_id, global::System.Int32 isWork)
        {
            member member = new member();
            member.mem_id = mem_id;
            member.isWork = isWork;
            return member;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mem_id
        {
            get
            {
                return _mem_id;
            }
            set
            {
                if (_mem_id != value)
                {
                    Onmem_idChanging(value);
                    ReportPropertyChanging("mem_id");
                    _mem_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mem_id");
                    Onmem_idChanged();
                }
            }
        }
        private global::System.Int32 _mem_id;
        partial void Onmem_idChanging(global::System.Int32 value);
        partial void Onmem_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userName
        {
            get
            {
                return _userName;
            }
            set
            {
                OnuserNameChanging(value);
                ReportPropertyChanging("userName");
                _userName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userName");
                OnuserNameChanged();
            }
        }
        private global::System.String _userName;
        partial void OnuserNameChanging(global::System.String value);
        partial void OnuserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userPwd
        {
            get
            {
                return _userPwd;
            }
            set
            {
                OnuserPwdChanging(value);
                ReportPropertyChanging("userPwd");
                _userPwd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userPwd");
                OnuserPwdChanged();
            }
        }
        private global::System.String _userPwd;
        partial void OnuserPwdChanging(global::System.String value);
        partial void OnuserPwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userRole
        {
            get
            {
                return _userRole;
            }
            set
            {
                OnuserRoleChanging(value);
                ReportPropertyChanging("userRole");
                _userRole = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userRole");
                OnuserRoleChanged();
            }
        }
        private Nullable<global::System.Int32> _userRole;
        partial void OnuserRoleChanging(Nullable<global::System.Int32> value);
        partial void OnuserRoleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private Nullable<global::System.Int32> _sex;
        partial void OnsexChanging(Nullable<global::System.Int32> value);
        partial void OnsexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creoSetup
        {
            get
            {
                return _creoSetup;
            }
            set
            {
                OncreoSetupChanging(value);
                ReportPropertyChanging("creoSetup");
                _creoSetup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creoSetup");
                OncreoSetupChanged();
            }
        }
        private global::System.String _creoSetup;
        partial void OncreoSetupChanging(global::System.String value);
        partial void OncreoSetupChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creoWorkSpace
        {
            get
            {
                return _creoWorkSpace;
            }
            set
            {
                OncreoWorkSpaceChanging(value);
                ReportPropertyChanging("creoWorkSpace");
                _creoWorkSpace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creoWorkSpace");
                OncreoWorkSpaceChanged();
            }
        }
        private global::System.String _creoWorkSpace;
        partial void OncreoWorkSpaceChanging(global::System.String value);
        partial void OncreoWorkSpaceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 isWork
        {
            get
            {
                return _isWork;
            }
            set
            {
                OnisWorkChanging(value);
                ReportPropertyChanging("isWork");
                _isWork = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isWork");
                OnisWorkChanged();
            }
        }
        private global::System.Int32 _isWork;
        partial void OnisWorkChanging(global::System.Int32 value);
        partial void OnisWorkChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("creo_dataModel", "FK_PARAMETE_REFERENCE_MEMBER", "parameters")]
        public EntityCollection<parameters> parameters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<parameters>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "parameters");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<parameters>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "parameters", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="creo_dataModel", Name="parameters")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class parameters : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 parameters 对象。
        /// </summary>
        /// <param name="parm_id">parm_id 属性的初始值。</param>
        /// <param name="isStandard">isStandard 属性的初始值。</param>
        /// <param name="isDelete">isDelete 属性的初始值。</param>
        public static parameters Createparameters(global::System.Int32 parm_id, global::System.Int32 isStandard, global::System.Int32 isDelete)
        {
            parameters parameters = new parameters();
            parameters.parm_id = parm_id;
            parameters.isStandard = isStandard;
            parameters.isDelete = isDelete;
            return parameters;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parm_id
        {
            get
            {
                return _parm_id;
            }
            set
            {
                if (_parm_id != value)
                {
                    Onparm_idChanging(value);
                    ReportPropertyChanging("parm_id");
                    _parm_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("parm_id");
                    Onparm_idChanged();
                }
            }
        }
        private global::System.Int32 _parm_id;
        partial void Onparm_idChanging(global::System.Int32 value);
        partial void Onparm_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mem_id
        {
            get
            {
                return _mem_id;
            }
            set
            {
                Onmem_idChanging(value);
                ReportPropertyChanging("mem_id");
                _mem_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mem_id");
                Onmem_idChanged();
            }
        }
        private Nullable<global::System.Int32> _mem_id;
        partial void Onmem_idChanging(Nullable<global::System.Int32> value);
        partial void Onmem_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> moshu
        {
            get
            {
                return _moshu;
            }
            set
            {
                OnmoshuChanging(value);
                ReportPropertyChanging("moshu");
                _moshu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("moshu");
                OnmoshuChanged();
            }
        }
        private Nullable<global::System.Decimal> _moshu;
        partial void OnmoshuChanging(Nullable<global::System.Decimal> value);
        partial void OnmoshuChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> deg
        {
            get
            {
                return _deg;
            }
            set
            {
                OndegChanging(value);
                ReportPropertyChanging("deg");
                _deg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deg");
                OndegChanged();
            }
        }
        private Nullable<global::System.Decimal> _deg;
        partial void OndegChanging(Nullable<global::System.Decimal> value);
        partial void OndegChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> kongjing
        {
            get
            {
                return _kongjing;
            }
            set
            {
                OnkongjingChanging(value);
                ReportPropertyChanging("kongjing");
                _kongjing = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kongjing");
                OnkongjingChanged();
            }
        }
        private Nullable<global::System.Decimal> _kongjing;
        partial void OnkongjingChanging(Nullable<global::System.Decimal> value);
        partial void OnkongjingChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> L
        {
            get
            {
                return _L;
            }
            set
            {
                OnLChanging(value);
                ReportPropertyChanging("L");
                _L = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("L");
                OnLChanged();
            }
        }
        private Nullable<global::System.Decimal> _L;
        partial void OnLChanging(Nullable<global::System.Decimal> value);
        partial void OnLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rongxieNum
        {
            get
            {
                return _rongxieNum;
            }
            set
            {
                OnrongxieNumChanging(value);
                ReportPropertyChanging("rongxieNum");
                _rongxieNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rongxieNum");
                OnrongxieNumChanged();
            }
        }
        private Nullable<global::System.Int32> _rongxieNum;
        partial void OnrongxieNumChanging(Nullable<global::System.Int32> value);
        partial void OnrongxieNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> zhoutaiD
        {
            get
            {
                return _zhoutaiD;
            }
            set
            {
                OnzhoutaiDChanging(value);
                ReportPropertyChanging("zhoutaiD");
                _zhoutaiD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zhoutaiD");
                OnzhoutaiDChanged();
            }
        }
        private Nullable<global::System.Decimal> _zhoutaiD;
        partial void OnzhoutaiDChanging(Nullable<global::System.Decimal> value);
        partial void OnzhoutaiDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> zhoutaiL
        {
            get
            {
                return _zhoutaiL;
            }
            set
            {
                OnzhoutaiLChanging(value);
                ReportPropertyChanging("zhoutaiL");
                _zhoutaiL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zhoutaiL");
                OnzhoutaiLChanged();
            }
        }
        private Nullable<global::System.Decimal> _zhoutaiL;
        partial void OnzhoutaiLChanging(Nullable<global::System.Decimal> value);
        partial void OnzhoutaiLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> jiancaoW
        {
            get
            {
                return _jiancaoW;
            }
            set
            {
                OnjiancaoWChanging(value);
                ReportPropertyChanging("jiancaoW");
                _jiancaoW = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jiancaoW");
                OnjiancaoWChanged();
            }
        }
        private Nullable<global::System.Decimal> _jiancaoW;
        partial void OnjiancaoWChanging(Nullable<global::System.Decimal> value);
        partial void OnjiancaoWChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> jiancaoH
        {
            get
            {
                return _jiancaoH;
            }
            set
            {
                OnjiancaoHChanging(value);
                ReportPropertyChanging("jiancaoH");
                _jiancaoH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jiancaoH");
                OnjiancaoHChanged();
            }
        }
        private Nullable<global::System.Decimal> _jiancaoH;
        partial void OnjiancaoHChanging(Nullable<global::System.Decimal> value);
        partial void OnjiancaoHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> kongdaoD
        {
            get
            {
                return _kongdaoD;
            }
            set
            {
                OnkongdaoDChanging(value);
                ReportPropertyChanging("kongdaoD");
                _kongdaoD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kongdaoD");
                OnkongdaoDChanged();
            }
        }
        private Nullable<global::System.Decimal> _kongdaoD;
        partial void OnkongdaoDChanging(Nullable<global::System.Decimal> value);
        partial void OnkongdaoDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> celeng
        {
            get
            {
                return _celeng;
            }
            set
            {
                OncelengChanging(value);
                ReportPropertyChanging("celeng");
                _celeng = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("celeng");
                OncelengChanged();
            }
        }
        private Nullable<global::System.Decimal> _celeng;
        partial void OncelengChanging(Nullable<global::System.Decimal> value);
        partial void OncelengChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> jiancaoR
        {
            get
            {
                return _jiancaoR;
            }
            set
            {
                OnjiancaoRChanging(value);
                ReportPropertyChanging("jiancaoR");
                _jiancaoR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jiancaoR");
                OnjiancaoRChanged();
            }
        }
        private Nullable<global::System.Decimal> _jiancaoR;
        partial void OnjiancaoRChanging(Nullable<global::System.Decimal> value);
        partial void OnjiancaoRChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 isStandard
        {
            get
            {
                return _isStandard;
            }
            set
            {
                OnisStandardChanging(value);
                ReportPropertyChanging("isStandard");
                _isStandard = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isStandard");
                OnisStandardChanged();
            }
        }
        private global::System.Int32 _isStandard;
        partial void OnisStandardChanging(global::System.Int32 value);
        partial void OnisStandardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> serail
        {
            get
            {
                return _serail;
            }
            set
            {
                OnserailChanging(value);
                ReportPropertyChanging("serail");
                _serail = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("serail");
                OnserailChanged();
            }
        }
        private Nullable<global::System.Int32> _serail;
        partial void OnserailChanging(Nullable<global::System.Int32> value);
        partial void OnserailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private Nullable<global::System.Int32> _type;
        partial void OntypeChanging(Nullable<global::System.Int32> value);
        partial void OntypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> kongdaoL
        {
            get
            {
                return _kongdaoL;
            }
            set
            {
                OnkongdaoLChanging(value);
                ReportPropertyChanging("kongdaoL");
                _kongdaoL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kongdaoL");
                OnkongdaoLChanged();
            }
        }
        private Nullable<global::System.Decimal> _kongdaoL;
        partial void OnkongdaoLChanging(Nullable<global::System.Decimal> value);
        partial void OnkongdaoLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 isDelete
        {
            get
            {
                return _isDelete;
            }
            set
            {
                OnisDeleteChanging(value);
                ReportPropertyChanging("isDelete");
                _isDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isDelete");
                OnisDeleteChanged();
            }
        }
        private global::System.Int32 _isDelete;
        partial void OnisDeleteChanging(global::System.Int32 value);
        partial void OnisDeleteChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("creo_dataModel", "FK_PARAMETE_REFERENCE_MEMBER", "member")]
        public member member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "member").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "member").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<member> memberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<member>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "member", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="creo_dataModel", Name="process")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class process : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 process 对象。
        /// </summary>
        /// <param name="procId">procId 属性的初始值。</param>
        /// <param name="isDelete">isDelete 属性的初始值。</param>
        public static process Createprocess(global::System.Int32 procId, global::System.Int32 isDelete)
        {
            process process = new process();
            process.procId = procId;
            process.isDelete = isDelete;
            return process;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 procId
        {
            get
            {
                return _procId;
            }
            set
            {
                if (_procId != value)
                {
                    OnprocIdChanging(value);
                    ReportPropertyChanging("procId");
                    _procId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("procId");
                    OnprocIdChanged();
                }
            }
        }
        private global::System.Int32 _procId;
        partial void OnprocIdChanging(global::System.Int32 value);
        partial void OnprocIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> machId
        {
            get
            {
                return _machId;
            }
            set
            {
                OnmachIdChanging(value);
                ReportPropertyChanging("machId");
                _machId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("machId");
                OnmachIdChanged();
            }
        }
        private Nullable<global::System.Int32> _machId;
        partial void OnmachIdChanging(Nullable<global::System.Int32> value);
        partial void OnmachIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> toolId
        {
            get
            {
                return _toolId;
            }
            set
            {
                OntoolIdChanging(value);
                ReportPropertyChanging("toolId");
                _toolId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("toolId");
                OntoolIdChanged();
            }
        }
        private Nullable<global::System.Int32> _toolId;
        partial void OntoolIdChanging(Nullable<global::System.Int32> value);
        partial void OntoolIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String procName
        {
            get
            {
                return _procName;
            }
            set
            {
                OnprocNameChanging(value);
                ReportPropertyChanging("procName");
                _procName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("procName");
                OnprocNameChanged();
            }
        }
        private global::System.String _procName;
        partial void OnprocNameChanging(global::System.String value);
        partial void OnprocNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 isDelete
        {
            get
            {
                return _isDelete;
            }
            set
            {
                OnisDeleteChanging(value);
                ReportPropertyChanging("isDelete");
                _isDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isDelete");
                OnisDeleteChanged();
            }
        }
        private global::System.Int32 _isDelete;
        partial void OnisDeleteChanging(global::System.Int32 value);
        partial void OnisDeleteChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="creo_dataModel", Name="toolDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class toolDetail : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 toolDetail 对象。
        /// </summary>
        /// <param name="todeId">todeId 属性的初始值。</param>
        /// <param name="isDelete">isDelete 属性的初始值。</param>
        public static toolDetail CreatetoolDetail(global::System.Int32 todeId, global::System.Int32 isDelete)
        {
            toolDetail toolDetail = new toolDetail();
            toolDetail.todeId = todeId;
            toolDetail.isDelete = isDelete;
            return toolDetail;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 todeId
        {
            get
            {
                return _todeId;
            }
            set
            {
                if (_todeId != value)
                {
                    OntodeIdChanging(value);
                    ReportPropertyChanging("todeId");
                    _todeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("todeId");
                    OntodeIdChanged();
                }
            }
        }
        private global::System.Int32 _todeId;
        partial void OntodeIdChanging(global::System.Int32 value);
        partial void OntodeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> toolId
        {
            get
            {
                return _toolId;
            }
            set
            {
                OntoolIdChanging(value);
                ReportPropertyChanging("toolId");
                _toolId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("toolId");
                OntoolIdChanged();
            }
        }
        private Nullable<global::System.Int32> _toolId;
        partial void OntoolIdChanging(Nullable<global::System.Int32> value);
        partial void OntoolIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String toolPara
        {
            get
            {
                return _toolPara;
            }
            set
            {
                OntoolParaChanging(value);
                ReportPropertyChanging("toolPara");
                _toolPara = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("toolPara");
                OntoolParaChanged();
            }
        }
        private global::System.String _toolPara;
        partial void OntoolParaChanging(global::System.String value);
        partial void OntoolParaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String toolParaValue
        {
            get
            {
                return _toolParaValue;
            }
            set
            {
                OntoolParaValueChanging(value);
                ReportPropertyChanging("toolParaValue");
                _toolParaValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("toolParaValue");
                OntoolParaValueChanged();
            }
        }
        private global::System.String _toolParaValue;
        partial void OntoolParaValueChanging(global::System.String value);
        partial void OntoolParaValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 isDelete
        {
            get
            {
                return _isDelete;
            }
            set
            {
                OnisDeleteChanging(value);
                ReportPropertyChanging("isDelete");
                _isDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isDelete");
                OnisDeleteChanged();
            }
        }
        private global::System.Int32 _isDelete;
        partial void OnisDeleteChanging(global::System.Int32 value);
        partial void OnisDeleteChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("creo_dataModel", "FK_TOOLDETA_REFERENCE_TOOLS", "tools")]
        public tools tools
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tools>("creo_dataModel.FK_TOOLDETA_REFERENCE_TOOLS", "tools").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tools>("creo_dataModel.FK_TOOLDETA_REFERENCE_TOOLS", "tools").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tools> toolsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tools>("creo_dataModel.FK_TOOLDETA_REFERENCE_TOOLS", "tools");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tools>("creo_dataModel.FK_TOOLDETA_REFERENCE_TOOLS", "tools", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="creo_dataModel", Name="tools")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tools : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tools 对象。
        /// </summary>
        /// <param name="toolId">toolId 属性的初始值。</param>
        /// <param name="isDelete">isDelete 属性的初始值。</param>
        public static tools Createtools(global::System.Int32 toolId, global::System.Int32 isDelete)
        {
            tools tools = new tools();
            tools.toolId = toolId;
            tools.isDelete = isDelete;
            return tools;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 toolId
        {
            get
            {
                return _toolId;
            }
            set
            {
                if (_toolId != value)
                {
                    OntoolIdChanging(value);
                    ReportPropertyChanging("toolId");
                    _toolId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("toolId");
                    OntoolIdChanged();
                }
            }
        }
        private global::System.Int32 _toolId;
        partial void OntoolIdChanging(global::System.Int32 value);
        partial void OntoolIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String toolName
        {
            get
            {
                return _toolName;
            }
            set
            {
                OntoolNameChanging(value);
                ReportPropertyChanging("toolName");
                _toolName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("toolName");
                OntoolNameChanged();
            }
        }
        private global::System.String _toolName;
        partial void OntoolNameChanging(global::System.String value);
        partial void OntoolNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 isDelete
        {
            get
            {
                return _isDelete;
            }
            set
            {
                OnisDeleteChanging(value);
                ReportPropertyChanging("isDelete");
                _isDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isDelete");
                OnisDeleteChanged();
            }
        }
        private global::System.Int32 _isDelete;
        partial void OnisDeleteChanging(global::System.Int32 value);
        partial void OnisDeleteChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String picName
        {
            get
            {
                return _picName;
            }
            set
            {
                OnpicNameChanging(value);
                ReportPropertyChanging("picName");
                _picName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("picName");
                OnpicNameChanged();
            }
        }
        private global::System.String _picName;
        partial void OnpicNameChanging(global::System.String value);
        partial void OnpicNameChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("creo_dataModel", "FK_TOOLDETA_REFERENCE_TOOLS", "toolDetail")]
        public EntityCollection<toolDetail> toolDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<toolDetail>("creo_dataModel.FK_TOOLDETA_REFERENCE_TOOLS", "toolDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<toolDetail>("creo_dataModel.FK_TOOLDETA_REFERENCE_TOOLS", "toolDetail", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
