//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("creo_dataModel", "FK_PARAMETE_REFERENCE_MEMBER", "member", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.member), "parameters", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.parameters), true)]

#endregion

namespace Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class creo_dataEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“creo_dataEntities”部分中的连接字符串初始化新 creo_dataEntities 对象。
        /// </summary>
        public creo_dataEntities() : base("name=creo_dataEntities", "creo_dataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 creo_dataEntities 对象。
        /// </summary>
        public creo_dataEntities(string connectionString) : base(connectionString, "creo_dataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 creo_dataEntities 对象。
        /// </summary>
        public creo_dataEntities(EntityConnection connection) : base(connection, "creo_dataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<member> member
        {
            get
            {
                if ((_member == null))
                {
                    _member = base.CreateObjectSet<member>("member");
                }
                return _member;
            }
        }
        private ObjectSet<member> _member;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<parameters> parameters
        {
            get
            {
                if ((_parameters == null))
                {
                    _parameters = base.CreateObjectSet<parameters>("parameters");
                }
                return _parameters;
            }
        }
        private ObjectSet<parameters> _parameters;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 member EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomember(member member)
        {
            base.AddObject("member", member);
        }
    
        /// <summary>
        /// 用于向 parameters EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToparameters(parameters parameters)
        {
            base.AddObject("parameters", parameters);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="creo_dataModel", Name="member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class member : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 member 对象。
        /// </summary>
        /// <param name="mem_id">mem_id 属性的初始值。</param>
        public static member Createmember(global::System.Int32 mem_id)
        {
            member member = new member();
            member.mem_id = mem_id;
            return member;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mem_id
        {
            get
            {
                return _mem_id;
            }
            set
            {
                if (_mem_id != value)
                {
                    Onmem_idChanging(value);
                    ReportPropertyChanging("mem_id");
                    _mem_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mem_id");
                    Onmem_idChanged();
                }
            }
        }
        private global::System.Int32 _mem_id;
        partial void Onmem_idChanging(global::System.Int32 value);
        partial void Onmem_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userName
        {
            get
            {
                return _userName;
            }
            set
            {
                OnuserNameChanging(value);
                ReportPropertyChanging("userName");
                _userName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userName");
                OnuserNameChanged();
            }
        }
        private global::System.String _userName;
        partial void OnuserNameChanging(global::System.String value);
        partial void OnuserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userPwd
        {
            get
            {
                return _userPwd;
            }
            set
            {
                OnuserPwdChanging(value);
                ReportPropertyChanging("userPwd");
                _userPwd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userPwd");
                OnuserPwdChanged();
            }
        }
        private global::System.String _userPwd;
        partial void OnuserPwdChanging(global::System.String value);
        partial void OnuserPwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userRole
        {
            get
            {
                return _userRole;
            }
            set
            {
                OnuserRoleChanging(value);
                ReportPropertyChanging("userRole");
                _userRole = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userRole");
                OnuserRoleChanged();
            }
        }
        private Nullable<global::System.Int32> _userRole;
        partial void OnuserRoleChanging(Nullable<global::System.Int32> value);
        partial void OnuserRoleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private Nullable<global::System.Int32> _sex;
        partial void OnsexChanging(Nullable<global::System.Int32> value);
        partial void OnsexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creoSetup
        {
            get
            {
                return _creoSetup;
            }
            set
            {
                OncreoSetupChanging(value);
                ReportPropertyChanging("creoSetup");
                _creoSetup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creoSetup");
                OncreoSetupChanged();
            }
        }
        private global::System.String _creoSetup;
        partial void OncreoSetupChanging(global::System.String value);
        partial void OncreoSetupChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creoWorkSpace
        {
            get
            {
                return _creoWorkSpace;
            }
            set
            {
                OncreoWorkSpaceChanging(value);
                ReportPropertyChanging("creoWorkSpace");
                _creoWorkSpace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creoWorkSpace");
                OncreoWorkSpaceChanged();
            }
        }
        private global::System.String _creoWorkSpace;
        partial void OncreoWorkSpaceChanging(global::System.String value);
        partial void OncreoWorkSpaceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> isWork
        {
            get
            {
                return _isWork;
            }
            set
            {
                OnisWorkChanging(value);
                ReportPropertyChanging("isWork");
                _isWork = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isWork");
                OnisWorkChanged();
            }
        }
        private Nullable<global::System.Int32> _isWork;
        partial void OnisWorkChanging(Nullable<global::System.Int32> value);
        partial void OnisWorkChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("creo_dataModel", "FK_PARAMETE_REFERENCE_MEMBER", "parameters")]
        public EntityCollection<parameters> parameters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<parameters>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "parameters");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<parameters>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "parameters", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="creo_dataModel", Name="parameters")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class parameters : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 parameters 对象。
        /// </summary>
        /// <param name="parm_id">parm_id 属性的初始值。</param>
        /// <param name="isDelete">isDelete 属性的初始值。</param>
        public static parameters Createparameters(global::System.Int32 parm_id, global::System.Int32 isDelete)
        {
            parameters parameters = new parameters();
            parameters.parm_id = parm_id;
            parameters.isDelete = isDelete;
            return parameters;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parm_id
        {
            get
            {
                return _parm_id;
            }
            set
            {
                if (_parm_id != value)
                {
                    Onparm_idChanging(value);
                    ReportPropertyChanging("parm_id");
                    _parm_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("parm_id");
                    Onparm_idChanged();
                }
            }
        }
        private global::System.Int32 _parm_id;
        partial void Onparm_idChanging(global::System.Int32 value);
        partial void Onparm_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mem_id
        {
            get
            {
                return _mem_id;
            }
            set
            {
                Onmem_idChanging(value);
                ReportPropertyChanging("mem_id");
                _mem_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mem_id");
                Onmem_idChanged();
            }
        }
        private Nullable<global::System.Int32> _mem_id;
        partial void Onmem_idChanging(Nullable<global::System.Int32> value);
        partial void Onmem_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> moshu
        {
            get
            {
                return _moshu;
            }
            set
            {
                OnmoshuChanging(value);
                ReportPropertyChanging("moshu");
                _moshu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("moshu");
                OnmoshuChanged();
            }
        }
        private Nullable<global::System.Decimal> _moshu;
        partial void OnmoshuChanging(Nullable<global::System.Decimal> value);
        partial void OnmoshuChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> deg
        {
            get
            {
                return _deg;
            }
            set
            {
                OndegChanging(value);
                ReportPropertyChanging("deg");
                _deg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deg");
                OndegChanged();
            }
        }
        private Nullable<global::System.Decimal> _deg;
        partial void OndegChanging(Nullable<global::System.Decimal> value);
        partial void OndegChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> kongjing
        {
            get
            {
                return _kongjing;
            }
            set
            {
                OnkongjingChanging(value);
                ReportPropertyChanging("kongjing");
                _kongjing = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kongjing");
                OnkongjingChanged();
            }
        }
        private Nullable<global::System.Decimal> _kongjing;
        partial void OnkongjingChanging(Nullable<global::System.Decimal> value);
        partial void OnkongjingChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> L
        {
            get
            {
                return _L;
            }
            set
            {
                OnLChanging(value);
                ReportPropertyChanging("L");
                _L = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("L");
                OnLChanged();
            }
        }
        private Nullable<global::System.Decimal> _L;
        partial void OnLChanging(Nullable<global::System.Decimal> value);
        partial void OnLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rongxieNum
        {
            get
            {
                return _rongxieNum;
            }
            set
            {
                OnrongxieNumChanging(value);
                ReportPropertyChanging("rongxieNum");
                _rongxieNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rongxieNum");
                OnrongxieNumChanged();
            }
        }
        private Nullable<global::System.Int32> _rongxieNum;
        partial void OnrongxieNumChanging(Nullable<global::System.Int32> value);
        partial void OnrongxieNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> zhoutaiD
        {
            get
            {
                return _zhoutaiD;
            }
            set
            {
                OnzhoutaiDChanging(value);
                ReportPropertyChanging("zhoutaiD");
                _zhoutaiD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zhoutaiD");
                OnzhoutaiDChanged();
            }
        }
        private Nullable<global::System.Decimal> _zhoutaiD;
        partial void OnzhoutaiDChanging(Nullable<global::System.Decimal> value);
        partial void OnzhoutaiDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> zhoutaiL
        {
            get
            {
                return _zhoutaiL;
            }
            set
            {
                OnzhoutaiLChanging(value);
                ReportPropertyChanging("zhoutaiL");
                _zhoutaiL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zhoutaiL");
                OnzhoutaiLChanged();
            }
        }
        private Nullable<global::System.Decimal> _zhoutaiL;
        partial void OnzhoutaiLChanging(Nullable<global::System.Decimal> value);
        partial void OnzhoutaiLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> jiancaoW
        {
            get
            {
                return _jiancaoW;
            }
            set
            {
                OnjiancaoWChanging(value);
                ReportPropertyChanging("jiancaoW");
                _jiancaoW = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jiancaoW");
                OnjiancaoWChanged();
            }
        }
        private Nullable<global::System.Decimal> _jiancaoW;
        partial void OnjiancaoWChanging(Nullable<global::System.Decimal> value);
        partial void OnjiancaoWChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> jiancaoH
        {
            get
            {
                return _jiancaoH;
            }
            set
            {
                OnjiancaoHChanging(value);
                ReportPropertyChanging("jiancaoH");
                _jiancaoH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jiancaoH");
                OnjiancaoHChanged();
            }
        }
        private Nullable<global::System.Decimal> _jiancaoH;
        partial void OnjiancaoHChanging(Nullable<global::System.Decimal> value);
        partial void OnjiancaoHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> kongdaoD
        {
            get
            {
                return _kongdaoD;
            }
            set
            {
                OnkongdaoDChanging(value);
                ReportPropertyChanging("kongdaoD");
                _kongdaoD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kongdaoD");
                OnkongdaoDChanged();
            }
        }
        private Nullable<global::System.Decimal> _kongdaoD;
        partial void OnkongdaoDChanging(Nullable<global::System.Decimal> value);
        partial void OnkongdaoDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> celeng
        {
            get
            {
                return _celeng;
            }
            set
            {
                OncelengChanging(value);
                ReportPropertyChanging("celeng");
                _celeng = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("celeng");
                OncelengChanged();
            }
        }
        private Nullable<global::System.Decimal> _celeng;
        partial void OncelengChanging(Nullable<global::System.Decimal> value);
        partial void OncelengChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> jiancaoR
        {
            get
            {
                return _jiancaoR;
            }
            set
            {
                OnjiancaoRChanging(value);
                ReportPropertyChanging("jiancaoR");
                _jiancaoR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jiancaoR");
                OnjiancaoRChanged();
            }
        }
        private Nullable<global::System.Decimal> _jiancaoR;
        partial void OnjiancaoRChanging(Nullable<global::System.Decimal> value);
        partial void OnjiancaoRChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> isStandard
        {
            get
            {
                return _isStandard;
            }
            set
            {
                OnisStandardChanging(value);
                ReportPropertyChanging("isStandard");
                _isStandard = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isStandard");
                OnisStandardChanged();
            }
        }
        private Nullable<global::System.Int32> _isStandard;
        partial void OnisStandardChanging(Nullable<global::System.Int32> value);
        partial void OnisStandardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> serail
        {
            get
            {
                return _serail;
            }
            set
            {
                OnserailChanging(value);
                ReportPropertyChanging("serail");
                _serail = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("serail");
                OnserailChanged();
            }
        }
        private Nullable<global::System.Int32> _serail;
        partial void OnserailChanging(Nullable<global::System.Int32> value);
        partial void OnserailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private Nullable<global::System.Int32> _type;
        partial void OntypeChanging(Nullable<global::System.Int32> value);
        partial void OntypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 isDelete
        {
            get
            {
                return _isDelete;
            }
            set
            {
                OnisDeleteChanging(value);
                ReportPropertyChanging("isDelete");
                _isDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isDelete");
                OnisDeleteChanged();
            }
        }
        private global::System.Int32 _isDelete;
        partial void OnisDeleteChanging(global::System.Int32 value);
        partial void OnisDeleteChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> kongdaoL
        {
            get
            {
                return _kongdaoL;
            }
            set
            {
                OnkongdaoLChanging(value);
                ReportPropertyChanging("kongdaoL");
                _kongdaoL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kongdaoL");
                OnkongdaoLChanged();
            }
        }
        private Nullable<global::System.Decimal> _kongdaoL;
        partial void OnkongdaoLChanging(Nullable<global::System.Decimal> value);
        partial void OnkongdaoLChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("creo_dataModel", "FK_PARAMETE_REFERENCE_MEMBER", "member")]
        public member member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "member").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "member").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<member> memberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<member>("creo_dataModel.FK_PARAMETE_REFERENCE_MEMBER", "member", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
